# Generated by Django 3.2.16 on 2023-11-26 06:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='dtype',
            field=models.CharField(default=datetime.datetime(2023, 11, 26, 6, 15, 28, 478177, tzinfo=utc), max_length=30),
            preserve_default=False,
        ),
    ]
