# Generated by Django 3.2.12 on 2023-11-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_deliveryaddress_dtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=50)),
                ('pro_desc', models.CharField(max_length=50)),
                ('pro_price', models.IntegerField()),
                ('pro_brand', models.CharField(max_length=50)),
                ('pro_rating', models.FloatField()),
                ('pro_image', models.ImageField(upload_to='uploads')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
