# Generated by Django 3.2.12 on 2023-11-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(default='smartphone', max_length=50),
            preserve_default=False,
        ),
    ]
