# Generated by Django 4.2.3 on 2023-12-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_deliverproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pro_desc',
            field=models.CharField(max_length=250),
        ),
    ]
