# Generated by Django 4.2.3 on 2023-12-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_products_pro_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='products',
            name='pro_brand',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='products',
            name='pro_name',
            field=models.CharField(max_length=150),
        ),
    ]
