# Generated by Django 4.2.3 on 2023-12-03 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_products_category_alter_products_pro_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverproducts',
            name='deliveron',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
