# Generated by Django 4.2.3 on 2023-12-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_contactus'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deliveryaddress',
            table='DeliveryAddress',
        ),
    ]
