# Generated by Django 4.2.3 on 2023-12-04 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_deliveryaddress_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactus',
            table='Contactus',
        ),
    ]
