# Generated by Django 4.2.3 on 2023-12-04 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_contactus_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='Products',
        ),
    ]
