# Generated by Django 4.2.3 on 2023-12-04 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_products_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deliverproducts',
            table='DeliverProducts',
        ),
    ]
