# Generated by Django 4.2.3 on 2023-12-04 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_deliverproducts_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='Cart',
        ),
    ]
