# Generated by Django 4.2.3 on 2023-12-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_blogs_table_alter_reviews_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('smartphone', 'Smartphone'), ('laptops', 'Laptops'), ('smartwatch', 'Smartwatch'), ('earphones', 'Earphones')], max_length=150),
        ),
    ]
