# Generated by Django 4.2.3 on 2023-12-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('smartphone', 'smartphone'), ('laptops', 'laptops'), ('smartwatch', 'Smartwatch'), ('earphones', 'Earphones')], max_length=150),
        ),
    ]
